{% set name = "ligo_hires_gps_time" %}
{% set version = "0.6.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://git.ligo.org/cds/software/cr_tools/ligo_hires_gps_time/-/archive/{{ version }}/{{ version }}.tar.gz
  sha256: 7b64655003acd662f2f8c4d8c18fe03cd1dc1bbfdc39dec8b754bd1a73cef152

build:
  skip: true  # [win or osx]
  error_overlinking: true
  error_overdepending: true
  number: 0

requirements:
  build:
    - python
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}

  host:
    - python
    - pip
    - ruff
    - maturin

  run:
    - python
    - cffi

test:
  requires:
    - pytest
    - pip
  source_files:
    - test_pip.py
    - test_thump.py
  commands:
    - pytest
    - pip check

about:
  home: https://git.ligo.org/cds/software/cr_tools/ligo_hires_gps_time
  dev_url: https://git.ligo.org/cds/software/cr_tools/ligo_hires_gps_time.git
  license: GPL-3.0-or-later
  license_family: GPL
  license_file:
    - COPYING
    - COPYING-GPL-3
    - THIRDPARTY-LICENSES.yml
  summary: Library for storing and manipulating hiresolution GPS time stamps for LIGO data streams.

extra:
  recipe-maintainers:
    - evonreis
