github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
  pkg_format: '2'
conda_forge_output_validation: true
build_platform: {osx_arm64: osx_64}
conda_build_tool: rattler-build
test: native_and_emulated

